# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'team14 (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for team14 (iOS)
    # add pods for desired Firebase products

    pod 'Firebase/Firestore'
    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
end

target 'team14 (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for team14 (macOS)

end
